config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users , controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :pictures, only: [:index, :new, :create, :edit, :update, :destroy]
  root 'pictures#index'

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    #adminカラムがtrueのユーザのみ、管理画面にアクセスできるように設定します。
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :omniauthable
  has_many :pictures
  mount_uploader :image, ImageUploader

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end
  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20],
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ## before_actionでdeviseのストロングパラメーターに
  ###nameカラムを追加するメソッドを実行します。
  before_action :configure_permitted_parameters, if: :devise_controller?

  PERMISSIBLE_ATTRIBUTES = %i(name image image_cache)

  #duve13例外処理
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, only: [:edit,:update,:destroy]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
        redirect_to pictures_path, notice: "写真を投稿しました"
        NoticeMailer.sendmail_picture(@picture).deliver
    else
      render action: 'new'
    end
  end


  def edit
  end

  def update
    @picture.update(picture_params)
    redirect_to pictures_path, notice: "写真を更新しました"
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "写真を削除しました"
  end

  private
    def picture_params
      params.require(:picture).permit(:image)
    end
    def set_picture
      @picture = Picture.find(params[:id])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.image, alt: user.name) if user.image?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'seedimage.png'
    end
    image_tag(img_url, alt: user.name)
  end
end


module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimilarInsta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<header>
		  <nav class="navbar navbar-default">
		    <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
			      </button>
			      <%= link_to root_path, class: "navbar-brand" do%>
			      	<i class="fa fa-instagram fa-lg fa-fw text-change" aria-hidden="true"></i><i class="fa fa-lg fa-fw text-change" aria-hidden="true">SimilarINSTA</i>
			      <% end %>
		    </div>
		    <!-- Collect the nav links, forms, and other content for toggling -->
		      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		        <ul class="nav navbar-nav navbar-right">
			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars fa-2x fa-fw text-change" aria-hidden="true"></i><span class="caret"></span></a>
			          <ul class="dropdown-menu">
			             <li><%= link_to pictures_path do %>
			             <i class="fa fa-camera fa-i text-change" aria-hidden="true">PICTURE</i>
			             <% end %>
			             </li>
			          </ul>
			        </li>
			        <% if user_signed_in? %>
				           <li>
				             <%= link_to edit_user_registration_path do%>
				             	<i class="fa fa-home fa-2x fa-fw text-change" aria-hidden="true"></i>
				             <% end %>
				           </li>
				           <li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out fa-2x text-change" aria-hidden="true"></i>
				           <% end %></li>
			        <% else %>
						   <li><%= link_to new_user_session_path do %><i class="fa fa-sign-in fa-2x text-change" aria-hidden="true"></i>
				           <% end %>
				           </li>
						   <li><%= link_to new_user_session_path do %><i class="fa fa-lg text-changeother" aria-hidden="true">UP</i>
				           <% end %></li>
					<% end %>
		        </ul>
		      </div><!-- /.navbar-collapse -->
		   </div><!-- /.container-fluid -->
		</nav>
		  </header>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@picture, url: pictures_path) do |f| %>
	<!-- dive13によってエラーメッセージ書き換え -->
	<%= f.error_messages! %>

	<%= f.label :image ,'画像を添付する', class:'btn' %>
	<%= f.file_field :image %>
	<br>

<%= f.submit 'POST', class: 'btn btn-primary btn-block' %>
<% end %>



<%= link_to "BACK INSTAGRAM HOME", pictures_path %>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>EDIT INSTAGRAM</h2>
    <div class="field">
    <%= form_for(@picture) do |f| %>
      <%= f.label :user_id %><br>
    ユーザーIDを選んでください
      <%= f.collection_select :user_id, User.all, :id, :id%>
    </div>
    <% end %>

    <%= render 'form' %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10 text-center instamain">
    <p><%= notice %></p>
  
      <%= link_to new_picture_path, class: 'btn btn-default' do %><div class ="postt">POST</div>
      <% end %>
	<br>
	<br>
	<br>

<div class="pokepoke">
<% @pictures.each do |picture| %>
	<div class = "cards-container">
	<div class="card">
	
	<!--  <div class="row">
 -->            <div class = "card-header">
	    <!-- <div class= "titlefield"> -->
	    		<br><br>
						<i class="fa fa-user fa-2x fa-fw" aria-hidden="true"></i><i class="fa" aria-hidden="true"><div class ="username-font"><%= picture.user.name %></div></i>

				</div>
				<br>
				<br>
				 	<!-- </div> -->
				<div class= "card-img">
				 		<%= image_tag(picture.image) %>
				</div>
				 	<!-- div class= "editdeletefield"> -->
				 <br>
				 <br>
				<div class= "card-comments">
						<%= link_to edit_picture_path(picture.id) do %>
						   <i class="fa fa-2x fa-pencil-square-o fa-fw" aria-hidden="true"></i>
						<% end %>
				        <%= link_to picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？'} do %><i class="fa fa-2x fa-trash" aria-hidden="true"></i>

				        <% end %>
			    </div>
			    <br>
			    <br>
			       <!--  </div> -->
		        
        </div>
	 <!-- </div> -->
	 
	 </div>
	</div>
	<% end %>
</div>


  </div>
</div>

app/views/pictures/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>POST INSTAGRAM</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>